project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: assets/dataidea-logo.png
  navbar:
    background: primary
    search: true
    right:
      - text: Home
        href: "https://web.dataidea.org/"
      - text: About
        menu:
          - text: About Us
            url: "https://dataidea.org/#about"
          - text: Privacy Policy
            url: "https://dataidea.org/privacy_policy.html"
          - text: Terms of Service
            url: "https://dataidea.org/terms_of_service.html"
      - text: Download
        menu:
          - text: Python 3 Beginner
            url: "https://dataidea.pythonanywhere.com/school/download-course-material/1"
          - text: Python Data Analysis
            url: "https://dataidea.pythonanywhere.com/school/download-course-material/2"
          - text: Pytorch
            url: "https://dataidea.pythonanywhere.com/school/download-course-material/3"
      - text: Subjects
        menu:
          - text: Data Science
            url: "https://science.dataidea.org"
          - text: Web Development
            url: "https://web.dataidea.org"
      - text: Resources
        menu:
          - text: Blog
            url: "https://blog.dataidea.org"
          - text: Forum
            url: "https://chat.whatsapp.com/GuCZRyJICgO3Y7MPvDQKhi"
          - text: French
            url: "https://french.dataidea.org"
          - text: Football
            url: "https://football.dataidea.org"
          - text: Movies
            url: "https://movies.dataidea.org"
      - text: Contact
        href: "https://www.dataidea.org/#contact"
  sidebar:
    style: "floating"
    twitter-card:
    creator: "@juma_shafara"
    site: "@datas_idea"

metadata-files: [nbdev.yml, sidebar.yml]
